variables:
  NODEJS_IMAGE: hub.lumigame.com/base/node:20.9.0-alpine-24h1.1

include:
  - project: "ci/core-cicd"
    ref: main
    file: "luminet.gitlab-ci.yml"

.unit_test_js:
  artifacts:
    when: always
    paths:
      - ./**/lcov.info
      - ./coverage
    reports:
      junit:
        - ./coverage/unit-tests.xml
    expire_in: 1 day
